# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  username: postgres
  password: vegeta@1993
  host: localhost
  database: locationads_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  username: postgres
  password: vegeta@1993
  host: localhost
  database: locationads_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  username: postgres
  password: vegeta@1993
  host: localhost
  database: locationads_production
  pool: 5
  timeout: 5000